# Generated by Django 4.1.1 on 2022-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='repsonse_by',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
